language: node_js
node_js:
- '10'
script:
- npm run build
- npm run test
deploy:
  provider: npm
  on:
    tags: true
    repo: joernb/redux-prefabs-connected-react-router
  email:
    secure: aQ5Ls1hBMt5rk2NJ938hmbevQX76wGHxckSidpv1xKoHLSZsAZ51p4SYxJEDanv6yJTRmgKpJX/0xde5fInNKULIyfOqUijLt51P+xBfttx0T+Xw/e+FiWB+BLQS6BoJSPzzB99KLPa+rRrabFzTQdXnPkHv2LJ9vRcr0HVqIJK2cL5+Aa+HdN35RPOVg4p+MuhQv2OyNjAkRWmXorWVxOTpFok2/MHy/8VNZSpFHByuih3y10K4CV2sji0DC6GUoNq/pnvalQ8CwVB9fzfvVHh6nOaUuRY1h1Z/htyFxV7zWT+VQr4gR5j6DhcfF4msdljhaqnu5LfT4qWxGPZBS5JGu47XI1vukd04LCos/9UFRJo8jpV4GRsLP9oBSKmsHM6sBjmlE3pCh6//1NsNVIfKXKunnlVr41AkW+5pgwRQxr8uSHPVkM8TqhAQvTtMdzunEvbkM9Y5z88B96rRPnylP8ugGt8Wv6vNQmEN3YUXW6eiBNYoFMi0vnn/IDE/zNhrttob4vF9b8u7kiMk00f7ve1g0CiIUXYcUscULmbHryo2NT5h4U8sYKJkEmnK5zHyXeY5nv06nFF5yMnVNVCKNf+8XNz17/rkrbTZ7mC/2E0H9Bb2iRQeHcrTa4aurQ+X/Sj8v+F3+yePESyI+RE0KGDnPyzFoustN1Y2EUw=
  api_key:
    secure: vWAePRDkd0qmalgM8AYKimd9zgMIhmMWHH/ixgL/mgfHYSxYc8bW2rzqMOqEnf5aKrmjqUC4GZwm6wAbOwtGu+decziPHwBpTXdnGoiRtnU6PwraVlsMB7M8xr7s+z/V5SQ8GcHrIAoTCrfnsbCX2e1WobubfIxCS9oCanI9S0syQcIcBtWbSSVTAPFapQk5D5DR+6NbshgMGo8GyeF1/IJwxJF1MSWFLt9TLuuv4NkVlCY5gWtSSxce+aXd2KG5yZXqZ+U8jYzDiZ4W1BmPa2j5Lvekg0FLoGaaSMzCAlOOGOHefgJxG/xGEr5t01C8TDkEcNfVUrmwC0hM1xHfeVS1l2xxjtuz9jB0aSmo80cFp+lKv7mYzLtMNBEIlz1jeBYWl/RKUUQOWRCSbhmh9QR9yCRvMEf7CWGpXG8PpSBsltfC9GazL56gJzK+gosdGjZEaxD5R1UUgUTmQNFBVrdmITx4kxOqdgZNKGvlXScN6KLDlDt2wNn0sfdKhO4G6iXSRYQ1Lh5CaXGdS/jDlExGXdSgQEOODEq0zNqBlPRKxiOKb7bYsnEMX8X4kfnEK9ts+HfNgGE7N5gQIn7ELgQh6mFP5UC8HwpavRv1PUv5M7PYae06ZSl1r/FwHz3MdxzfCfgH36nVxkIKxCdLtP2juM+E7aPo+BXKsl+T5Hw=
